name: Update Deploy Repository on Release

on:
  release:
    types: [published]

jobs:
  update-early-adopters:
    runs-on: ubuntu-latest

    steps:
      # checks out the core repository and extracts the latest commit SHA and release tag name
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract latest commit SHA
      id: extract_sha
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Extract release tag name
      id: extract_tag_name
      run: echo "::set-output name=tag_name::${{ github.event.release.tag_name }}"

    # checkout deploy repo, make changes, and open a pull request
    - name: Checkout deploy repository
      uses: actions/checkout@v3
      with:
        repository: 'ctmackay/deploy'
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        ref: 'main' # Change to your default branch if it's not 'main'
        path: 'deploy'

    - name: Make changes in the deploy repository (early adopters)
      run: |
        ${GITHUB_WORKSPACE}/deploy/src/release_updater.sh early ${{ steps.extract_tag_name.outputs.tag_name }} ${{ steps.extract_sha.outputs.sha }}
      shell: bash

    - name: Create and push branch and open pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        path: 'deploy'
        delete-branch: true
        commit-message: 'Prerelease update'
        title: 'Update Early adopters ${{ steps.extract_tag_name.outputs.tag_name }}'
        body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
        base: 'main' # Target branch in the deploy repository
        branch: 'update-early-adopters-${{ github.sha }}'

    # checkout deploy repo, make changes, and open a pull request
    - name: Checkout deploy repository
      uses: actions/checkout@v3
      with:
        repository: 'ctmackay/deploy'
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        ref: 'main' # Change to your default branch if it's not 'main'
        path: 'deploy'

    - name: Make changes in the deploy repository (early adopters)
      run: |
        ${GITHUB_WORKSPACE}/deploy/src/release_updater.sh prod ${{ steps.extract_tag_name.outputs.tag_name }} ${{ steps.extract_sha.outputs.sha }}
      shell: bash

    - name: Create and push branch and open pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        path: 'deploy'
        delete-branch: true
        commit-message: 'prod update'
        title: 'Update prod ${{ steps.extract_tag_name.outputs.tag_name }}'
        body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
        base: 'main' # Target branch in the deploy repository
        branch: 'update-prod-${{ github.sha }}'

    # checkout deploy repo, make changes, and open a pull request
    - name: Checkout deploy repository
      uses: actions/checkout@v3
      with:
        repository: 'ctmackay/deploy'
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        ref: 'main' # Change to your default branch if it's not 'main'
        path: 'deploy'

    - name: Make changes in the deploy repository (early adopters)
      run: |
        ${GITHUB_WORKSPACE}/deploy/src/release_updater.sh release ${{ steps.extract_tag_name.outputs.tag_name }} ${{ steps.extract_sha.outputs.sha }}
      shell: bash

    - name: Create and push branch and open pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        path: 'deploy'
        delete-branch: true
        commit-message: 'release update'
        title: 'Update release ${{ steps.extract_tag_name.outputs.tag_name }}'
        body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
        base: 'main' # Target branch in the deploy repository
        branch: 'update-release-${{ github.sha }}'
