name: Update Deploy Repository on Release

on:
  release:
    types: [published]

jobs:
  update-deploy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deploy repository
      uses: actions/checkout@v3
      with:
        repository: 'ctmackay/deploy'
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        ref: 'main' # Change to your default branch if it's not 'main'
        path: 'deploy'

    - name: Make changes in the deploy repository
      run: |
        echo ${{ github.sha }} >> ${GITHUB_WORKSPACE}/deploy/src/core-sha.txt
      shell: bash

    - name: Commit and push changes
      run: |
        cd ${GITHUB_WORKSPACE}/deploy
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Automated update from core repository release"
        git push
      shell: bash

    - name: Create Pull Request in deploy repository
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        path: 'deploy'
        commit-message: 'Update deploy repository'
        title: 'Automated PR: Update from core repository'
        body: 'This is an automated pull request to update from the core repository.'
        base: 'main' # Target branch in the deploy repository
        branch: 'update-from-core-${{ github.sha }}'
