name: Update Deploy Repository on Release

on:
  release:
    types: [published]

jobs:
  update-early-adopters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract latest commit SHA
      id: extract_sha
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Extract release tag name
      id: extract_tag_name
      run: echo "::set-output name=tag_name::${{ github.event.release.tag_name }}"


    - name: Checkout deploy repository
      uses: actions/checkout@v3
      with:
        repository: 'ctmackay/deploy'
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        ref: 'main' # Change to your default branch if it's not 'main'
        path: 'deploy'

    - name: Make changes in the deploy repository (early adopters)
      run: |
        # Stage and commit changes for early adopters
        cp ${GITHUB_WORKSPACE}/deploy/src/template.py ${GITHUB_WORKSPACE}/deploy/src/settings.py
        sed -i 's/REPLACE_ME_GIT_TAG/${{ steps.extract_tag_name.outputs.tag_name }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
        sed -i 's/REPLACE_ME_GIT_SHA/${{ steps.extract_sha.outputs.sha }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
        sed -i 's/REPLACE_ME_CONFIG_FOLDER/logistics-core-early/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
        sed -i 's/REPLACE_ME_SLS_FILENAME/prod_early_adopter.sls/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py

      shell: bash

    - name: Create and push branch and open pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        path: 'deploy'
        delete-branch: true
        commit-message: 'Prerelease update'
        title: 'Update Early adopters ${{ steps.extract_tag_name.outputs.tag_name }}'
        body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
        base: 'main' # Target branch in the deploy repository
        branch: 'update-from-core-${{ github.sha }}'


  update-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract latest commit SHA
      id: extract_sha
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Extract release tag name
      id: extract_tag_name
      run: echo "::set-output name=tag_name::${{ github.event.release.tag_name }}"


    - name: Checkout deploy repository
      uses: actions/checkout@v3
      with:
        repository: 'ctmackay/deploy'
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        ref: 'main' # Change to your default branch if it's not 'main'
        path: 'deploy'

    - name: Make changes in the deploy repository (prod)
      run: |
        # Stage and commit changes for early adopters settings_prod.py
        cp ${GITHUB_WORKSPACE}/deploy/src/template.py ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
        sed -i 's/REPLACE_ME_GIT_TAG/${{ steps.extract_tag_name.outputs.tag_name }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
        sed -i 's/REPLACE_ME_GIT_SHA/${{ steps.extract_sha.outputs.sha }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
        sed -i 's/REPLACE_ME_CONFIG_FOLDER/logistics-core-early/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
        sed -i 's/REPLACE_ME_SLS_FILENAME/prod_early_adopter.sls/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py

      shell: bash

    - name: Create and push branch and open pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
        path: 'deploy'
        delete-branch: true
        commit-message: 'Prerelease update'
        title: 'Update general population ${{ steps.extract_tag_name.outputs.tag_name }}'
        body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
        base: 'main' # Target branch in the deploy repository
        branch: 'update-prod-from-core-${{ github.sha }}'
